data:
  root_dir: "data/processed"
  image_size: [512, 512]
  batch_size: 1
  num_workers: 8

model:
  name: "unet"
  lr: 1e-4

trainer:
  max_epochs: 50
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"
  log_every_n_steps: 10

logger:
  project: "photochrom-ai"
