model:
  name: unet
  lr: 0.0005

data:
  root_dir: data/processed
  batch_size: 16
  image_size: [512, 512]
  num_workers: 8

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: auto
  precision: 16
  log_every_n_steps: 50
  val_check_interval: 0.5

logger:
  project: photochrom-ai

hydra:
  run:
    dir: training/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    level: INFO
    formatters:
      simple:
        format: '[%(asctime)s] [%(levelname)s] - %(message)s'
    handlers:
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.run.dir}/train.log
        mode: a
    root:
      level: INFO
      handlers: [file]
